### ISSUE TITLE
Inconsistent reports for SMART data

### ISSUE THREAD

**Issue by rice1204** [eschava/psmqtt#33]
Thanks for adding in SMART support! 
Sadly, I've been fighting with psmqtt to get it working consistently (this is on windows)

I have 8 drives (5 hdd, 3 ssd), but at any given time, only some of the drives report statistics. The very unusual thing is out of the 8 drives, sometimes 4 will report smart data, sometimes 6 will report, sometimes, depending on their mood, only 3 of them will report. 

The ones which aren't reporting properly show vague messages. I'm guessing the problem stems from something upstream (pysmart? smartctl?). I'm eager to trace this bug, but don't even know where to start. Any suggestions appreciated.

pqmqtt.log (in this case, sdb report is OK, but sdc is failing. sometimes it might be the other way around)
```
[2023-01-30 12:00:19,392] INFO mqttc.publish('psmqtt/naruto/smart/sdb/temperature', '30')
[2023-01-30 12:00:19,395] DEBUG run_task(smart/sdc/temperature, smart/sdc/temperature)
[2023-01-30 12:00:20,978] INFO mqttc.publish('psmqtt/naruto/smart/sdc/temperature/error', ''NoneType' object has no attribute 'groups'')
[2023-01-30 12:00:20,978] ERROR run_task caught: smart/sdc/temperature : 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "C:\psmqtt\src\task.py", line 153, in run_task
    payload = get_value(task)
  File "C:\psmqtt\src\handlers.py", line 802, in get_value
    value = handler.handle(tail)
  File "C:\psmqtt\src\handlers.py", line 532, in handle
    self.device = SmartDevice(self.name)
  File "C:\Python\Python39\lib\site-packages\pySMART\device.py", line 295, in __init__
    self.update()
  File "C:\Python\Python39\lib\site-packages\pySMART\device.py", line 1023, in update
    parsed = re.compile(
AttributeError: 'NoneType' object has no attribute 'groups'
```

C:\psmqtt> smartctl --scan-open
```
/dev/sda -d ata # /dev/sda, ATA device
/dev/sdb -d ata # /dev/sdb, ATA device
/dev/sdc -d ata # /dev/sdc, ATA device
/dev/sdd -d ata # /dev/sdd, ATA device
/dev/sde -d ata # /dev/sde, ATA device
/dev/sdf -d ata # /dev/sdf, ATA device
/dev/sdg -d ata # /dev/sdg, ATA device
/dev/sdh -d usbprolific # /dev/sdh [USB Prolific], ATA device
/dev/csmi1,2 -d ata # /dev/csmi1,2, ATA device
/dev/csmi1,4 -d ata # /dev/csmi1,4, ATA device
/dev/csmi1,5 -d ata # /dev/csmi1,5, ATA device

```

C:\psmqtt> smartctl -a /dev/sdc
```
smartctl 7.3 2022-02-28 r5338 [x86_64-w64-mingw32-w10-21H2] (sf-7.3-1)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     HGST Deskstar NAS
Device Model:     HGST HDN724040ALE640
Serial Number:    PK2334PBKLGXVT
LU WWN Device Id: 5 000cca 23df2ad3d
Firmware Version: MJAOA5E0
User Capacity:    4,000,787,030,016 bytes [4.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    7200 rpm
Form Factor:      3.5 inches
Device is:        In smartctl database 7.3/5319
ATA Version is:   ATA8-ACS T13/1699-D revision 4
SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Mon Jan 30 12:30:45 2023 PST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x82)	Offline data collection activity
					was completed without error.
					Auto Offline Data Collection: Enabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(   24) seconds.
Offline data collection
capabilities: 			 (0x5b) SMART execute Offline immediate.
					Auto Offline data collection on/off support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					No Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   1) minutes.
Extended self-test routine
recommended polling time: 	 ( 560) minutes.
SCT capabilities: 	       (0x003d)	SCT Status supported.
					SCT Error Recovery Control supported.
					SCT Feature Control supported.
					SCT Data Table supported.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000b   100   100   016    Pre-fail  Always       -       0
  2 Throughput_Performance  0x0005   136   136   054    Pre-fail  Offline      -       81
  3 Spin_Up_Time            0x0007   185   185   024    Pre-fail  Always       -       447 (Average 389)
  4 Start_Stop_Count        0x0012   100   100   000    Old_age   Always       -       288
  5 Reallocated_Sector_Ct   0x0033   100   100   005    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000b   100   100   067    Pre-fail  Always       -       0
  8 Seek_Time_Performance   0x0005   124   124   020    Pre-fail  Offline      -       33
  9 Power_On_Hours          0x0012   091   091   000    Old_age   Always       -       65397
 10 Spin_Retry_Count        0x0013   100   100   060    Pre-fail  Always       -       0
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       178
192 Power-Off_Retract_Count 0x0032   098   098   000    Old_age   Always       -       3103
193 Load_Cycle_Count        0x0012   098   098   000    Old_age   Always       -       3103
194 Temperature_Celsius     0x0002   187   187   000    Old_age   Always       -       32 (Min/Max 14/63)
196 Reallocated_Event_Count 0x0032   100   100   000    Old_age   Always       -       0
197 Current_Pending_Sector  0x0022   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0008   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x000a   200   200   000    Old_age   Always       -       65

SMART Error Log Version: 1
ATA Error Count: 65 (device log contains only the most recent five errors)
	CR = Command Register [HEX]
	FR = Features Register [HEX]
	SC = Sector Count Register [HEX]
	SN = Sector Number Register [HEX]
	CL = Cylinder Low Register [HEX]
	CH = Cylinder High Register [HEX]
	DH = Device/Head Register [HEX]
	DC = Device Command Register [HEX]
	ER = Error register [HEX]
	ST = Status register [HEX]
Powered_Up_Time is measured from power on, and printed as
DDd+hh:mm:SS.sss where DD=days, hh=hours, mm=minutes,
SS=sec, and sss=millisec. It "wraps" after 49.710 days.

Error 65 occurred at disk power-on lifetime: 7 hours (0 days + 7 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 01 cf 51 2d 01  Error: ICRC, ABRT 1 sectors at LBA = 0x012d51cf = 19747279

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  35 00 08 c8 51 2d 40 00      07:19:30.545  WRITE DMA EXT
  ef 02 00 00 00 00 40 00      07:19:30.544  SET FEATURES [Enable write cache]
  ef 03 46 00 00 00 40 00      07:19:30.544  SET FEATURES [Set transfer mode]
  c6 00 10 00 00 00 40 00      07:19:30.544  SET MULTIPLE MODE
  ec 00 00 00 00 00 40 00      07:19:30.542  IDENTIFY DEVICE

Error 64 occurred at disk power-on lifetime: 7 hours (0 days + 7 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 01 cf 51 2d 01  Error: ICRC, ABRT 1 sectors at LBA = 0x012d51cf = 19747279

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  35 00 08 c8 51 2d 40 00      07:17:32.347  WRITE DMA EXT
  ef 02 00 00 00 00 40 00      07:17:32.347  SET FEATURES [Enable write cache]
  ef 03 46 00 00 00 40 00      07:17:32.346  SET FEATURES [Set transfer mode]
  c6 00 10 00 00 00 40 00      07:17:32.346  SET MULTIPLE MODE
  ec 00 00 00 00 00 40 00      07:17:32.345  IDENTIFY DEVICE

Error 63 occurred at disk power-on lifetime: 6 hours (0 days + 6 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 01 df 4f 2d 01  Error: ICRC, ABRT 1 sectors at LBA = 0x012d4fdf = 19746783

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  35 00 08 d8 4f 2d 40 00      06:57:32.618  WRITE DMA EXT
  35 00 08 80 eb ff 40 00      06:57:32.290  WRITE DMA EXT
  ef 02 00 00 00 00 40 00      06:57:32.290  SET FEATURES [Enable write cache]
  ef 03 46 00 00 00 40 00      06:57:32.289  SET FEATURES [Set transfer mode]
  c6 00 10 00 00 00 40 00      06:57:32.289  SET MULTIPLE MODE

Error 62 occurred at disk power-on lifetime: 6 hours (0 days + 6 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 01 df 4f 2d 01  Error: ICRC, ABRT 1 sectors at LBA = 0x012d4fdf = 19746783

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  35 00 08 d8 4f 2d 40 00      06:57:31.637  WRITE DMA EXT
  ef 02 00 00 00 00 40 00      06:57:31.637  SET FEATURES [Enable write cache]
  ef 03 46 00 00 00 40 00      06:57:31.636  SET FEATURES [Set transfer mode]
  c6 00 10 00 00 00 40 00      06:57:31.636  SET MULTIPLE MODE
  ec 00 00 00 00 00 40 00      06:57:31.635  IDENTIFY DEVICE

Error 61 occurred at disk power-on lifetime: 6 hours (0 days + 6 hours)
  When the command that caused the error occurred, the device was active or idle.

  After command completion occurred, registers were:
  ER ST SC SN CL CH DH
  -- -- -- -- -- -- --
  84 51 01 df 4f 2d 01  Error: ICRC, ABRT 1 sectors at LBA = 0x012d4fdf = 19746783

  Commands leading to the command that caused the error were:
  CR FR SC SN CL CH DH DC   Powered_Up_Time  Command/Feature_Name
  -- -- -- -- -- -- -- --  ----------------  --------------------
  35 00 08 d8 4f 2d 40 00      06:55:38.749  WRITE DMA EXT
  35 00 08 d0 4f 2d 40 00      06:55:38.749  WRITE DMA EXT
  ef 02 00 00 00 00 40 00      06:55:38.748  SET FEATURES [Enable write cache]
  ef 03 46 00 00 00 40 00      06:55:38.748  SET FEATURES [Set transfer mode]
  c6 00 10 00 00 00 40 00      06:55:38.748  SET MULTIPLE MODE

SMART Self-test log structure revision number 1
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%      2785         -

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.


```

**Comment by rice1204** [comment]
Sorry, please disregard. Still having the problem, but figured out it runs fine when launched with python directly from CLI. The issue only appears when I'm running python as a windows service with NSSM (non-sucking service manager).

I'm guessing it's a permissions issue. Thx!

**Comment by f18m** [comment]
Thanks @rice1204  for reporting back, closing this issue then.
